name: WarpBonus
version: 1.0.0
main: com.flyaway.warpbonus.WarpBonusPlugin
api-version: 1.21
author: FlyAwayMaking
website: https://github.com/flyawaymaking
depend: [LuckPerms]

commands:
  warpbonus:
    description: Управление бонусными варпами игроков
    usage: /warpbonus <add|set|check|list> [игрок] [количество]
    permission: warps.bonus.manage

permissions:
  warps.bonus.manage:
    description: Доступ к управлению бонусными варпами
    default: op
