name: ${name}
main: ${group}.${name}
version: ${version}
api-version: 1.21
author: FlyAwayMaking
website: https://github.com/flyawaymaking
depend: [LuckPerms]
softdepend: [PlaceholderAPI]

commands:
  bonusaxwarp:
    description: Управление бонусными варпами игроков
    usage: /<command> <add|set|check|list> [игрок] [количество]
  aliases: ['bonuswarp']

permissions:
  bonusaxwarp.manage:
    description: Доступ к управлению бонусными варпами
    default: op
